USE MASTER;
GO
CREATE DATABASE BD_CALIDAD;
GO
USE [BD_CALIDAD];
GO

/****** Object:  Table [dbo].[Usuario]    Script Date: 11/02/2016 19:54:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERFIL](
	[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[NOMBRE] [nvarchar](50) NOT NULL,	
)

GO

CREATE TABLE [dbo].[USUARIO](
	[ID] INT IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[ID_PERFIL] INT NOT NULL,
	[CONTRASENA] [nvarchar](15) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID)
)

GO

CREATE TABLE [dbo].[EVENTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[FECHA_EVENTO] DATETIME NOT NULL,
	[ID_USUARIO_REGISTRA] [INT] NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO_REGISTRA) REFERENCES USUARIO(ID)
)

GO

CREATE TABLE [dbo].[ASOCIADO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[CEDULA] INT NOT NULL,
	[ESTADO1] BIT NOT NULL,
	[ESTADO2] BIT NOT NULL,
	[CORREO] [nvarchar](15) NOT NULL,
	PRIMARY KEY (ID)
)

GO


CREATE TABLE [dbo].[BITACORA_ASISTENCIA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO_REGISTRA] INT NOT NULL,
	[HORA_REGISTRO] DATETIME NOT NULL,
	[ID_ASOCIADO] INT NOT NULL,
	[ESTADO] BIT NOT NULL,
	[ID_EVENTO] INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO_REGISTRA) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_ASOCIADO) REFERENCES ASOCIADO(ID),
	FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID)
)

GO

CREATE TABLE [dbo].[CIERRE_MESA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_EVENTO] INT NOT NULL,
	[ID_USUARIO_REGISTRA] INT NOT NULL,
	[ESTADO] BIT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO_REGISTRA) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID)
)

GO




/*** INSERTS ***/

INSERT INTO PERFIL(NOMBRE) VALUES('ADMINISTRADOR');
INSERT INTO PERFIL(NOMBRE) VALUES('REGISTRADOR');

